"""api unicode->number values

Revision ID: 17a464c338fd
Revises: 2bc12ed800b9
Create Date: 2015-08-10 23:17:58.961817

"""

# revision identifiers, used by Alembic.
revision = '17a464c338fd'
down_revision = '2bc12ed800b9'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('growth_apis', 'aa_api_cur',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'aa_api_prev',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'aa_grow',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'aa_num',
               existing_type=mysql.VARCHAR(length=7),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'aa_targ',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'acs_46',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'acs_core',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'acs_k3',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'ai_api_cur',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'ai_api_prev',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'ai_grow',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'ai_num',
               existing_type=mysql.VARCHAR(length=7),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'ai_targ',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'api_cur',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'api_prev',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'as_api_cur',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'as_api_prev',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'as_grow',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'as_num',
               existing_type=mysql.VARCHAR(length=7),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'as_targ',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'avg_ed',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'cbmob',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'col_grad',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'cw_chse',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'cw_chsm',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'cw_cste',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'cw_csth',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'cw_cstm',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'cw_sci',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'cwm2_28',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'cwm2_91',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'cws2_91',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'cws_91',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'di_api_cur',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'di_api_prev',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'di_grow',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'di_num',
               existing_type=mysql.VARCHAR(length=7),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'di_targ',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'dmob',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'el_api_cur',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'el_api_prev',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'el_grow',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'el_num',
               existing_type=mysql.VARCHAR(length=7),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'el_targ',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'emer',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'enroll',
               existing_type=mysql.VARCHAR(length=7),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'fi_api_cur',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'fi_api_prev',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'fi_grow',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'fi_num',
               existing_type=mysql.VARCHAR(length=7),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'fi_targ',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'full',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'grad_sch',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'growth',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'hi_api_cur',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'hi_api_prev',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'hi_grow',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'hi_num',
               existing_type=mysql.VARCHAR(length=7),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'hi_targ',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'hsg',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'meals',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'med_cur',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'med_prev',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'mr_api_cur',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'mr_api_prev',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'mr_grow',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'mr_num',
               existing_type=mysql.VARCHAR(length=7),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'mr_targ',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'not_hsg',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'p_di',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'p_el',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'p_gate',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'p_miged',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'p_rfep',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'par_opt',
               existing_type=mysql.VARCHAR(length=6),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pchs_e',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pchs_m',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pcst_e28',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pcst_e91',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pcst_h28',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pcst_h91',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pcst_ls10',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pcst_m28',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pcst_m91',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pcst_s28',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pcst_s91',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pcstm2_28',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pcstm2_91',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pcsts2_91',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pct_aa',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pct_ai',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pct_as',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pct_fi',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pct_hi',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pct_mr',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pct_pi',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pct_resp',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pct_wh',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pen_2',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pen_35',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pen_6',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pen_78',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pen_911',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pi_api_cur',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pi_api_prev',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pi_grow',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pi_num',
               existing_type=mysql.VARCHAR(length=7),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pi_targ',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'sd_api_cur',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'sd_api_prev',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'sd_grow',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'sd_num',
               existing_type=mysql.VARCHAR(length=7),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'sd_targ',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'sim_rank',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'some_col',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'st_rank',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'target',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'tested',
               existing_type=mysql.VARCHAR(length=7),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'tot_28',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'tot_91',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'valid',
               existing_type=mysql.VARCHAR(length=7),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'vchs_e',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'vchs_m',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'vcst_e28',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'vcst_e91',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'vcst_h28',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'vcst_h91',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'vcst_ls10',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'vcst_m28',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'vcst_m91',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'vcst_s28',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'vcst_s91',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'vcstm2_28',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'vcstm2_91',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'vcsts2_91',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'wh_api_cur',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'wh_api_prev',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'wh_grow',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'wh_num',
               existing_type=mysql.VARCHAR(length=7),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'wh_targ',
               existing_type=mysql.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_column('growth_apis', 'dname')
    op.drop_column('growth_apis', 'charter')
    op.drop_column('growth_apis', 'sname')
    op.drop_column('growth_apis', 'cname')
    op.alter_column('schools', 'charter',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schools', 'charter',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.add_column('growth_apis', sa.Column('cname', mysql.VARCHAR(length=15), nullable=True))
    op.add_column('growth_apis', sa.Column('sname', mysql.VARCHAR(length=40), nullable=True))
    op.add_column('growth_apis', sa.Column('charter', mysql.VARCHAR(length=1), nullable=True))
    op.add_column('growth_apis', sa.Column('dname', mysql.VARCHAR(length=30), nullable=True))
    op.alter_column('growth_apis', 'wh_targ',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'wh_num',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=7),
               existing_nullable=True)
    op.alter_column('growth_apis', 'wh_grow',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'wh_api_prev',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'wh_api_cur',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'vcsts2_91',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('growth_apis', 'vcstm2_91',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('growth_apis', 'vcstm2_28',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('growth_apis', 'vcst_s91',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('growth_apis', 'vcst_s28',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('growth_apis', 'vcst_m91',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('growth_apis', 'vcst_m28',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('growth_apis', 'vcst_ls10',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('growth_apis', 'vcst_h91',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('growth_apis', 'vcst_h28',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('growth_apis', 'vcst_e91',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('growth_apis', 'vcst_e28',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('growth_apis', 'vchs_m',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('growth_apis', 'vchs_e',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('growth_apis', 'valid',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=7),
               existing_nullable=True)
    op.alter_column('growth_apis', 'tot_91',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('growth_apis', 'tot_28',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('growth_apis', 'tested',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=7),
               existing_nullable=True)
    op.alter_column('growth_apis', 'target',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'st_rank',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'some_col',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'sim_rank',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'sd_targ',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'sd_num',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=7),
               existing_nullable=True)
    op.alter_column('growth_apis', 'sd_grow',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'sd_api_prev',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'sd_api_cur',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pi_targ',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pi_num',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=7),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pi_grow',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pi_api_prev',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pi_api_cur',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pen_911',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pen_78',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pen_6',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pen_35',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pen_2',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pct_wh',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pct_resp',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pct_pi',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pct_mr',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pct_hi',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pct_fi',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pct_as',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pct_ai',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pct_aa',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pcsts2_91',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pcstm2_91',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pcstm2_28',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pcst_s91',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pcst_s28',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pcst_m91',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pcst_m28',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pcst_ls10',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pcst_h91',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pcst_h28',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pcst_e91',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pcst_e28',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pchs_m',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('growth_apis', 'pchs_e',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('growth_apis', 'par_opt',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=6),
               existing_nullable=True)
    op.alter_column('growth_apis', 'p_rfep',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'p_miged',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'p_gate',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'p_el',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'p_di',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'not_hsg',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'mr_targ',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'mr_num',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=7),
               existing_nullable=True)
    op.alter_column('growth_apis', 'mr_grow',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'mr_api_prev',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'mr_api_cur',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'med_prev',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'med_cur',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'meals',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'hsg',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'hi_targ',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'hi_num',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=7),
               existing_nullable=True)
    op.alter_column('growth_apis', 'hi_grow',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'hi_api_prev',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'hi_api_cur',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'growth',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'grad_sch',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'full',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'fi_targ',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'fi_num',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=7),
               existing_nullable=True)
    op.alter_column('growth_apis', 'fi_grow',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'fi_api_prev',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'fi_api_cur',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'enroll',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=7),
               existing_nullable=True)
    op.alter_column('growth_apis', 'emer',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'el_targ',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'el_num',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=7),
               existing_nullable=True)
    op.alter_column('growth_apis', 'el_grow',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'el_api_prev',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'el_api_cur',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'dmob',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'di_targ',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'di_num',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=7),
               existing_nullable=True)
    op.alter_column('growth_apis', 'di_grow',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'di_api_prev',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'di_api_cur',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'cws_91',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'cws2_91',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'cwm2_91',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'cwm2_28',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'cw_sci',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'cw_cstm',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'cw_csth',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'cw_cste',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'cw_chsm',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'cw_chse',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'col_grad',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'cbmob',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'avg_ed',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'as_targ',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'as_num',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=7),
               existing_nullable=True)
    op.alter_column('growth_apis', 'as_grow',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'as_api_prev',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'as_api_cur',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'api_prev',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'api_cur',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'ai_targ',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'ai_num',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=7),
               existing_nullable=True)
    op.alter_column('growth_apis', 'ai_grow',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'ai_api_prev',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'ai_api_cur',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'acs_k3',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'acs_core',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'acs_46',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'aa_targ',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'aa_num',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=7),
               existing_nullable=True)
    op.alter_column('growth_apis', 'aa_grow',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'aa_api_prev',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    op.alter_column('growth_apis', 'aa_api_cur',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)
    ### end Alembic commands ###
