"""growth rtype change

Revision ID: 2413d2c6e9b3
Revises: 132bec437be2
Create Date: 2015-08-11 15:15:52.695060

"""

# revision identifiers, used by Alembic.
revision = '2413d2c6e9b3'
down_revision = '132bec437be2'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schools', 'charter',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('growth_apis', 'rtype',
               existing_type=mysql.ENUM('D','S','X'),
               type_=mysql.VARCHAR(length=1),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schools', 'charter',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('growth_apis', 'rtype',
               existing_type=mysql.VARCHAR(length=1),
               type_=mysql.ENUM('D','S','X'),
               existing_nullable=True)
    ### end Alembic commands ###
