"""api year -> int

Revision ID: 2bc12ed800b9
Revises: 44569b3ba371
Create Date: 2015-08-10 16:47:14.135862

"""

# revision identifiers, used by Alembic.
revision = '2bc12ed800b9'
down_revision = '44569b3ba371'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('growth_apis', 'year',
               existing_type=sa.DATE(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('schools', 'charter',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schools', 'charter',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('growth_apis', 'year',
               existing_type=sa.Integer(),
               type_=sa.DATE(),
               existing_nullable=True)
    ### end Alembic commands ###
