"""base api table diff additions

Revision ID: 739184ee45d
Revises: 59f4e36c3847
Create Date: 2015-08-18 00:00:44.112197

"""

# revision identifiers, used by Alembic.
revision = '739184ee45d'
down_revision = '59f4e36c3847'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_apis', sa.Column('cma_adj', sa.Integer(), nullable=True))
    op.add_column('base_apis', sa.Column('cma_adj_ela', sa.Integer(), nullable=True))
    op.add_column('base_apis', sa.Column('cma_adj_math', sa.Integer(), nullable=True))
    op.add_column('base_apis', sa.Column('cma_adj_sci', sa.Integer(), nullable=True))
    op.add_column('base_apis', sa.Column('cw_nrtl', sa.Float(), nullable=True))
    op.add_column('base_apis', sa.Column('cw_nrtm', sa.Float(), nullable=True))
    op.add_column('base_apis', sa.Column('cw_nrtr', sa.Float(), nullable=True))
    op.add_column('base_apis', sa.Column('cw_nrts', sa.Float(), nullable=True))
    op.add_column('base_apis', sa.Column('pnrt_l28', sa.Float(), nullable=True))
    op.add_column('base_apis', sa.Column('pnrt_m28', sa.Float(), nullable=True))
    op.add_column('base_apis', sa.Column('pnrt_r28', sa.Float(), nullable=True))
    op.add_column('base_apis', sa.Column('pnrt_s28', sa.Float(), nullable=True))
    op.add_column('base_apis', sa.Column('vnrt_l28', sa.Integer(), nullable=True))
    op.add_column('base_apis', sa.Column('vnrt_m28', sa.Integer(), nullable=True))
    op.add_column('base_apis', sa.Column('vnrt_r28', sa.Integer(), nullable=True))
    op.add_column('base_apis', sa.Column('vnrt_s28', sa.Integer(), nullable=True))
    op.alter_column('schools', 'charter',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schools', 'charter',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_column('base_apis', 'vnrt_s28')
    op.drop_column('base_apis', 'vnrt_r28')
    op.drop_column('base_apis', 'vnrt_m28')
    op.drop_column('base_apis', 'vnrt_l28')
    op.drop_column('base_apis', 'pnrt_s28')
    op.drop_column('base_apis', 'pnrt_r28')
    op.drop_column('base_apis', 'pnrt_m28')
    op.drop_column('base_apis', 'pnrt_l28')
    op.drop_column('base_apis', 'cw_nrts')
    op.drop_column('base_apis', 'cw_nrtr')
    op.drop_column('base_apis', 'cw_nrtm')
    op.drop_column('base_apis', 'cw_nrtl')
    op.drop_column('base_apis', 'cma_adj_sci')
    op.drop_column('base_apis', 'cma_adj_math')
    op.drop_column('base_apis', 'cma_adj_ela')
    op.drop_column('base_apis', 'cma_adj')
    ### end Alembic commands ###
