"""new growthapi id

Revision ID: 9c52668cef8
Revises: 17a464c338fd
Create Date: 2015-08-10 23:26:12.516479

"""

# revision identifiers, used by Alembic.
revision = '9c52668cef8'
down_revision = '17a464c338fd'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('growth_apis', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Unicode(length=18),
               existing_nullable=False)
    op.alter_column('schools', 'charter',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schools', 'charter',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('growth_apis', 'id',
               existing_type=sa.Unicode(length=18),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
    ### end Alembic commands ###
